version: "3.8"
services:
  squid:
    image: docker.io/ubuntu/squid:5.6-22.10_beta
    container_name: squid
    volumes:
      - ./volumes/log:/var/log/squid
      - ./volumes/squid:/etc/squid
    ports:
      - "3128:3128/tcp"
    restart: unless-stopped
  nginx-alpine-slim:
    image: docker.io/nginx:1.27.0-alpine3.19-slim
    container_name: nginx-alpine-slim
    volumes:
      - ./volumes/nginx:/usr/share/nginx/html
    ports:
      - "8080:80/tcp"
    restart: unless-stopped