version: "3.8"
services:
  squid:
    image: ubuntu/squid:5.6-22.10_beta
    container_name: squid
    volumes:
      - ./volumes/log:/var/log/squid
      - ./volumes/squid:/etc/squid
    ports:
      - "3128:3128/tcp"
    restart: unless-stopped